from fastapi import FastAPI, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from typing import List
import pydicom
import io
import numpy as np
import cv2
from ultralytics import YOLO

# Disable syntax highlighting in Swagger UI to prevent RangeError on large arrays
app = FastAPI(swagger_ui_parameters={"syntaxHighlight": False})

# Add CORS middleware to allow requests from the Lovable frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows all origins (e.g. Lovable browser preview)
    allow_credentials=False,  # Must be False when allow_origins=["*"]
    allow_methods=["*"],  # Allows all methods (POST, GET, OPTIONS, etc.)
    allow_headers=["*"],
)


# Custom ASGI Middleware to strictly satisfy Chrome's Private Network Access (PNA) Policy.
# This attaches the 'Access-Control-Allow-Private-Network: true' header to all responses,
# including OPTIONS preflight responses generated by CORSMiddleware.
class PNAMiddleware:
    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            return await self.app(scope, receive, send)

        async def send_wrapper(message):
            if message["type"] == "http.response.start":
                headers = message.setdefault("headers", [])
                headers.append((b"access-control-allow-private-network", b"true"))
            await send(message)

        await self.app(scope, receive, send_wrapper)


app.add_middleware(PNAMiddleware)

# Load YOLO model globally to avoid reloading on each request
model = YOLO("yolo_best_corrected2.pt")


@app.get("/")
def read_root():
    return "YOLO App is running. Visit /docs for API documentations."


def pre_process_dicom(file_bytes: bytes) -> np.ndarray:
    ds = pydicom.dcmread(io.BytesIO(file_bytes))
    pixel_array = ds.pixel_array.astype(np.float32)

    # 1. Rescale
    if "RescaleSlope" in ds and "RescaleIntercept" in ds:
        pixel_array = pixel_array * ds.RescaleSlope + ds.RescaleIntercept

    # 2. Windowing logic if present
    if "WindowCenter" in ds and "WindowWidth" in ds:
        center = (
            ds.WindowCenter
            if isinstance(ds.WindowCenter, (int, float))
            else ds.WindowCenter[0]
        )
        width = (
            ds.WindowWidth
            if isinstance(ds.WindowWidth, (int, float))
            else ds.WindowWidth[0]
        )

        vmin = center - width / 2.0
        vmax = center + width / 2.0
        pixel_array = np.clip(pixel_array, vmin, vmax)
        pixel_array = (pixel_array - vmin) / (vmax - vmin) * 255.0
    else:
        # Fallback to simple min/max normalization
        img_min = np.min(pixel_array)
        img_max = np.max(pixel_array)
        if img_max > img_min:
            pixel_array = (pixel_array - img_min) / (img_max - img_min) * 255.0
        else:
            pixel_array = np.zeros_like(pixel_array)

    pixel_array = np.clip(pixel_array, 0, 255).astype(np.uint8)

    # Convert to 3 channels for YOLO
    if len(pixel_array.shape) == 2:
        pixel_array = cv2.cvtColor(pixel_array, cv2.COLOR_GRAY2RGB)
    elif len(pixel_array.shape) == 3 and pixel_array.shape[2] == 1:
        pixel_array = cv2.cvtColor(pixel_array, cv2.COLOR_GRAY2RGB)

    return pixel_array


@app.post("/segment")
async def segment_dicoms(files: List[UploadFile] = File(...)):
    parsed_files = []

    for file in files:
        file_bytes = await file.read()
        try:
            # Read just enough to get the InstanceNumber for sorting, to match frontend
            ds = pydicom.dcmread(io.BytesIO(file_bytes), stop_before_pixels=True)
            instance_num = int(ds.InstanceNumber) if "InstanceNumber" in ds else 0
        except Exception:
            # Skip invalid DICOM files
            continue

        parsed_files.append((instance_num, file.filename or "", file_bytes))

    # Sort by InstanceNumber first, then filename to perfectly match front-end sorting logic
    parsed_files.sort(key=lambda x: (x[0], x[1]))

    output_masks = []

    for slice_index, (_, _, file_bytes) in enumerate(parsed_files):
        try:
            img = pre_process_dicom(file_bytes)
        except Exception:
            continue

        # Run YOLO inference
        results = model.predict(img, verbose=False)
        result = results[0]

        H, W = img.shape[:2]

        # We will populate this mask map with class values
        # Initialize background as 0
        mask_map = np.zeros((H, W), dtype=np.uint8)
        class_confidences = {}

        if result.masks is not None and result.boxes is not None:
            # zip masks and boxes to get coordinates and class
            masks_xy = result.masks.xy
            cls_ids = result.boxes.cls.cpu().numpy()
            confs = result.boxes.conf.cpu().numpy()

            # Draw predictions ordered by confidence (highest confidence overriding the others)
            order = np.argsort(confs)
            for idx in order:
                poly = masks_xy[idx]
                # Filter out empty polygons
                if len(poly) == 0:
                    continue

                cls_id = int(cls_ids[idx])
                conf_val = float(confs[idx])

                # Depending on how the classes are configured (1-indexed vs 0-indexed),
                # you might need to adjust this value. e.g. mapping 0 to 1 to avoid background blending.
                # Assuming the YOLO classes directly correspond to the integer needed mapping.
                pixel_val = cls_id

                # Prevent YOLO class 0 from completely blending into the 0-value background.
                # Unless your specific setup assumes '0' is an explicit target logic,
                # mapping it to '1' is the most standard approach if class 0 is a detected object.
                if pixel_val == 0:
                    pixel_val = 1

                class_confidences[pixel_val] = conf_val

                poly_int = np.int32(poly)
                cv2.fillPoly(mask_map, [poly_int], pixel_val)

        class_errors = {}
        total_pixels = H * W
        for class_val in class_confidences.keys():
            class_pixels = int(np.sum(mask_map == class_val))
            if class_pixels > 0.5 * total_pixels:
                class_errors[class_val] = True
            else:
                class_errors[class_val] = False

        output_masks.append(
            {
                "sliceIndex": slice_index,
                "width": W,
                "height": H,
                "data": mask_map.flatten().tolist(),
                "confidences": class_confidences,
                "errors": class_errors,
            }
        )

    return {"masks": output_masks}
